default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432  

development:
  <<: *default
  database: journal_development

test:
  <<: *default
  database: journal_test

production:
  <<: *default
  database: journal_production